DTS-34986 Central AuthNAuth Spring Boot upgrade
PublicisSapient/PSknowHOW pull request #1012
Opened 2024-05-27 09:56 UTC by tibi-iordache

Upgrading the Central AuthNAuth Spring Boot version to 3.2 and Java version to 17.

2024-05-30 13:49 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/controller/APITokenController.java
why the API token is removed? Generate API token API uses for Connect central AUTH to Client system for specific API. to call via API token. we did not used to token- for example delete-User API - it will be only via API token,  we are restricting some API to any User AUTH cookie token.

2024-05-30 13:59 UTC, hirbabar requested changes

2024-05-30 13:59 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/SAMLAuthenticationService.java
> +	void saveSamlData(Saml2AuthenticatedPrincipal principal, HttpServletResponse response);
it will save data in DB first time only right?

2024-05-31 11:07 UTC, tibi-iordache commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/SAMLAuthenticationService.java
> +	void saveSamlData(Saml2AuthenticatedPrincipal principal, HttpServletResponse response);
Yes, it will save the user if it doesn't exists in the db yet, or if the user is present it will update the user information with the one extracted from the SAML principal.

2024-05-31 11:11 UTC, tibi-iordache commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/dto/ResetPasswordRequestDTO.java
> +	@NotNull
I think it is the way Git shows the differences that makes it a bit weird.
Basically I have removed the generate API key request dto since all the BE to BE requests will be validated using the authCookie. 
I have also moved all the DTOs inside the service folder because for this concrete example, the DTO is only used in the Central auth service.
It also helps if we want to integrate the central auth service with another spring boot service that uses a java version < 17. Because it doesn't need to add the dependency to that common lib anymore, that would generate problems when using it with different versions of java.

2024-05-31 11:48 UTC, tibi-iordache commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/controller/APITokenController.java
I think this was what we discussed at the end of the last PI, that we would drop the API tokens and rely solely on the cookies. 
For the delete user API(which I think you refer to the /reject/{username} one?) wouldn't make sense that only the SUPERADMIN could delete those users? and as such, you will first need to be logged in as SUPERADMIN.

2024-05-31 11:50 UTC, tibi-iordache commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/controller/APITokenController.java
I mean, if we really need some token for quick BE to BE communication (for example to replicate the users from central auth into other client applications databases) we could write one in the application.yml and used it from there in the JWT Filter. 
I don't think we need such a complicated mechanism for creating a new token every x months and saving it in the db.
Please correct me if I am missing something.

2024-06-28 05:37 UTC, hirbabar requested changes
check security related data removed and codeql issues

2024-06-28 05:37 UTC, hirbabar commented on central-auth-service/authapi/src/main/resources/application-local.yml
> +    password: postgres
remove password

2024-06-28 05:37 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/impl/StandardAuthenticationServiceImpl.java
> +				authentication.getAuthorities()
in Saml case Authorities parameter is set null , and the standard case set authentication.getAuthorities() so that JWT issue occurs mentioned in grp

2024-06-28 05:37 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/impl/StandardAuthenticationServiceImpl.java
> +		log.info("ForgotPasswordServiceImpl: Validate the token {}", token);
token will be remove from logs

2024-06-28 05:37 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/impl/StandardAuthenticationServiceImpl.java
> +		log.info("ForgotPasswordServiceImpl: Reset token is {}", resetPasswordRequest.getResetToken());
token will be remove from logs

2024-06-28 05:37 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/impl/StandardAuthenticationServiceImpl.java
> +		} else {
multiple time same issue codeQl and sonar issue if any file then check

2024-06-28 05:37 UTC, hirbabar commented on central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/impl/UserServiceImpl.java
> +						 .firstName(user.getFirstName()).lastName(user.getLastName()).displayName(user.getDisplayName())
approved and verified flag is needed

2024-10-08 06:24 UTC, hirbabar commented
this PR changes is merged in https://github.com/PublicisSapient/PSknowHOW/pull/1520 PR. so not reqied this PR so that i am closeing this PR

2024-10-08 06:24 UTC, closed without merging