Dts 30485 user filters
PublicisSapient/PSknowHOW pull request #1097
Opened 2024-06-13 05:48 UTC by risshukl0

2024-06-19 09:42 UTC, hirbabar commented on Kubernetes/Kubernetes-manifest/customapi.yaml
> +          image: speedtools.azurecr.io/knowhow-customapi:11.0.0-SNAPSHOT
version should check

2024-06-24 13:01 UTC, HinPublicis requested changes

2024-06-24 17:51 UTC, brahmanand1 commented on UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
> +      this.helperService.setBackupOfFilterSelectionState({ 'primary_level': selectedFilters });
While taking backup (storing on service layer)  of filters , instead of nodeId can we keep whole object so that from backup we can access every property i.e. nodeId, parentID, lablename etc ? @risshukl0

2024-06-24 17:51 UTC, brahmanand1 commented on UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
> +        this.combinedDate = `${startDateFormatted} - ${endDateFormatted}`;
Can we move this code (line no 360 - 367) in separate method since this looks independent code ?@risshukl0

2024-06-24 17:51 UTC, brahmanand1 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +              this.helperService.setBackupOfFilterSelectionState({ 'parent_level': this.selectedLevel })
Again while take backup of parent_level we just saving level only . if possible can we save whole object i.e level , name, id etc

2024-06-24 17:51 UTC, brahmanand1 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +    this.helperService.setBackupOfFilterSelectionState({ 'parent_level': this.selectedLevel.toLowerCase(), 'primary_level': null });
Again while take backup of parent_level we just saving level only . Can we store whole object while taking backup of parent_filter , primary_filter , addtional_filter  throughout filter components ? @risshukl0

2024-06-24 17:51 UTC, brahmanand1 commented on UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts
> +            this.helperService.setBackupOfFilterSelectionState({ 'primary_level': this.selectedFilters });
pls keep whole object in primary_level if possible @risshukl0

2024-06-24 17:51 UTC, brahmanand1 commented on UI/src/app/module/app-routing.module.ts
> +/***************************NEW UI End**************************************** */
Pls remove unnecessary components import , since not using in this module.

2024-06-24 17:55 UTC, brahmanand1 commented on UI/src/app/dashboard/dora/dora.component.html
> -</ng-container> -->
@HinPublicis This recommendations component was temporarily commented on every dashboard or no longer needed ? @risshukl0 pls check with @HinPublicis

2024-06-27 08:06 UTC, risshukl0 commented on UI/src/app/dashboard/executive/executive.component.ts
> +    selectedTab = 'iteration';
We have not made any change in Executive component....not sure about this

2024-06-27 08:07 UTC, risshukl0 commented on UI/src/app/dashboard/iteration/iteration.component.ts
> +      if (this.service.currentSelectedSprint?.sprintState.toLowerCase() === 'active' && showDSVorNot) { // && showDailyStandup) {
Not required Hinal

2024-06-27 08:07 UTC, risshukl0 commented on UI/src/app/dashboardv2/dashboard-v2/dashboard-v2.component.css
> +:host ::ng-deep .main-container label {
Because we don't want to change fonts in old UI

2024-06-27 08:08 UTC, risshukl0 commented on UI/src/app/dashboardv2/executive-v2/executive-v2.component.spec.ts
> +  const fakeDoraKpis = require('../../../test/resource/fakeDoraKpis.json');
done

2024-06-27 08:09 UTC, risshukl0 commented on UI/src/app/dashboardv2/executive-v2/executive-v2.component.spec.ts
> +  const configGlobalData = [
done

2024-06-27 08:10 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.css
> +    font-family: Poppins_Regular, sans-serif;
required, as we are not declaring fonts globally

2024-06-27 08:10 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +  additionalFilterLevels = ['release', 'sprint', 'sqd'];
No other way to identify additional filters

2024-06-27 08:11 UTC, risshukl0 commented on UI/src/app/page-not-found/page-not-found.component.css
> +div {
No change done in Page-not-found-component. Not sure about this.

2024-06-27 12:18 UTC, risshukl0 commented on UI/src/app/dashboardv2/nav-v2/nav-new.component.ts
> +                    setTimeout(() => {
Done!!

2024-06-27 12:34 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +          setTimeout(() => {
Done!!

2024-06-27 13:18 UTC, HinPublicis commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +  additionalFilterLevels = ['release', 'sprint', 'sqd'];
@risshukl0 There is one way to identify additional filters. We have done it in old UI. From an api response all the items who have level greater that project level comes under additional filters. Please change this.

2024-06-27 13:19 UTC, HinPublicis commented on UI/src/app/dashboard/iteration/iteration.component.html
> -  <app-recommendations [filterData]="filterApplyData" [kpiList]="kpiList"></app-recommendations>
@brahmanand1 this is on hold because of Ana's changes. Till then we can't give to testing.

2024-06-27 14:44 UTC, risshukl0 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/userboardconfig/rest/UserBoardConfigController.java
> +		if (userBoardConfigDTO == null) {
Only once @hirbabar , in the nav-new component

2024-06-27 14:51 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.ts
> +        }
I think you fixed it 👍

2024-06-27 14:52 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
> +            ]
It would be the same thing @brahmanand1

2024-06-27 14:54 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
> +        this.combinedDate = `${startDateFormatted} - ${endDateFormatted}`;
Done

2024-06-27 14:55 UTC, risshukl0 commented on UI/src/app/module/app-routing.module.ts
> +/***************************NEW UI End**************************************** */
Done

2024-06-28 04:17 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +  additionalFilterLevels = ['release', 'sprint', 'sqd'];
Done as per old UI.

2024-06-28 06:00 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +              this.helperService.setBackupOfFilterSelectionState({ 'parent_level': this.selectedLevel })
In this particular case, the whole object is being saved.

2024-06-28 06:00 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
> +      this.helperService.setBackupOfFilterSelectionState({ 'primary_level': selectedFilters });
In this particular case, the list of objects is being saved.

2024-06-28 06:27 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts
> +    this.helperService.setBackupOfFilterSelectionState({ 'parent_level': this.selectedLevel.toLowerCase(), 'primary_level': null });
On most dashboards, parent level is string only. Wherever it is not, we are saving the nodeId of the selected value. This nodeId is used to extract all details.

2024-06-28 06:27 UTC, risshukl0 commented on UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts
> +            this.helperService.setBackupOfFilterSelectionState({ 'primary_level': this.selectedFilters });
selectedFilters is a list of whole objects only @brahmanand1

2024-06-28 06:31 UTC, brahmanand1 approved these changes

2024-06-28 07:46 UTC, HinPublicis approved these changes

2024-07-08 05:12 UTC, merged