bug fix
PublicisSapient/PSknowHOW pull request #1353
Opened 2024-08-16 05:53 UTC by spal-sapient

2024-08-16 06:50 UTC, brahmanand1 requested changes

2024-08-16 06:50 UTC, brahmanand1 commented on UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
> +    let colorsArr = ['#6079C5', '#FFB587', '#D48DEF', '#FBCF5F', '#A4F6A5', '#9FECFF']
@spal-sapient why are we changing project indication static colors?

2024-08-21 08:23 UTC, prabasak23 approved these changes

2024-08-22 06:22 UTC, brahmanand1 approved these changes

2024-08-22 06:22 UTC, brahmanand1 approved these changes

2024-08-22 06:24 UTC, merged