Dts 40072 lazy loading iteration
PublicisSapient/PSknowHOW pull request #1549
Opened 2024-10-07 07:00 UTC by spal-sapient

2024-10-07 08:19 UTC, risshukl0 requested changes
@spal-sapient why so many changes required? And in switch case, why are we handling single KPIs?

2024-10-07 09:15 UTC, spal-sapient commented
> @spal-sapient why so many changes required? And in switch case, why are we handling single KPIs?

changes are make sure will are calling api on inner tab switch, I have replace the existing if else with switch case, single KPIs logic was existing before, I didn't change the existing logic.

2024-10-07 09:20 UTC, risshukl0 approved these changes

2024-10-07 09:24 UTC, brahmanand1 approved these changes

2024-10-15 04:41 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1100/ChangeIterationKPIsGroupId.java
> +@ChangeUnit(id = "r_change_iteration_kpis_groupId", order = "011001", author = "purgupta2", systemVersion = "10.3.0")
if going in this release, please change the order/version as per requirement

2024-10-15 10:09 UTC, ananthpal approved these changes

2024-10-15 10:14 UTC, merged