hide toools and connections based on flag
PublicisSapient/PSknowHOW pull request #276
Opened 2023-10-26 12:35 UTC by brahmanand1

2023-10-30 06:58 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/rest/GlobalFieldsController.java
> + *
add author name

2023-10-30 07:06 UTC, Chittauri commented
@kunkambl  use "/api/configDetails" instead of creating new data class.

2023-11-01 05:40 UTC, Chittauri approved these changes

2023-11-22 07:58 UTC, shunaray requested changes
Also make db changes for installation scripts both mongock & database_scripts

2023-11-22 08:15 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_810/RepoToolProviderUrlChange.java
> +package com.publicissapient.kpidashboard.apis.mongock.rollback.release_810;
add copyright

2023-11-22 08:16 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_810/RepoToolProviderUrlChange.java
> +@ChangeUnit(id = "r_repo_tool_provider_url_change", order = "08110", author = "kunkambl", systemVersion = "8.1.0")
use suppress warning, add author comment

2023-11-22 08:17 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_810/RepoToolProviderUrlChange.java
> +package com.publicissapient.kpidashboard.apis.mongock.upgrade.release_810;
add copyright, author and suppress warning

2023-11-22 09:15 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/service/ProcessorServiceImpl.java
> +				String processorName = p.getProcessorName();
optimize the check

2023-11-22 09:21 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/connection/service/ConnectionServiceImpl.java
> +		if (Boolean.TRUE.equals(customApiConfig.getIsRepoToolEnable()) && type.equalsIgnoreCase(TOOL_GITHUB)) {
add todo--debbie

2023-11-22 10:29 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/service/ProcessorServiceImpl.java
> +				if (shouldAddToList) {
boolean toggle= true;
toggle= toggle && !processorName.equalsIgnoreCase(ProcessorConstants.GITLAB);

toggle= toggle && !processorName.equalsIgnoreCase(ProcessorConstants.GITHUB);....... use this

2023-11-22 10:44 UTC, Chittauri approved these changes

2023-11-22 10:45 UTC, shunaray approved these changes

2023-11-22 10:47 UTC, merged