Dtc 20731 defect count by rca
PublicisSapient/PSknowHOW pull request #409
Opened 2023-01-18 09:21 UTC by ashutoshy14

DtS 20731 defect count by rca with UI integration added

2023-01-18 09:32 UTC, hirbabar approved these changes

2023-01-18 09:32 UTC, hirbabar commented on UI/src/environments/environment.ts
revert this local file changes

2023-01-18 09:32 UTC, hirbabar commented on customapi/src/main/resources/application-dev.properties
revert this local file changes

2023-01-18 09:32 UTC, hirbabar commented on customapi/src/main/resources/application.properties
>  spring.data.mongodb.port=27017
revert this local file changes

2023-01-18 09:32 UTC, hirbabar commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DefectCountByRCAServiceImpl.java
> +import java.util.*;
import and file formatting

2023-01-18 09:59 UTC, hirbabar requested changes
resolved conflicts

2023-01-18 11:07 UTC, hirbabar requested changes

2023-01-18 11:07 UTC, hirbabar commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DefectCountByRCAServiceImpl.java
> +							}
needed to proper dev testing

2023-01-19 07:30 UTC, hirbabar commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DefectCountByRCAServiceImpl.java
> +			LOGGER.info("Closure Possible Today -> Requested sprint : {}", leafNode.getName());
define meaningful variable name for ex. variable name should be totalIssues

2023-01-23 05:29 UTC, ashutoshy14 reviewed
Review changes

2023-02-24 11:55 UTC, closed without merging