Dts 26918 backlog count by status
PublicisSapient/PSknowHOW pull request #46
Opened 2023-07-13 08:40 UTC by aksshriv1

2023-07-13 08:45 UTC, Chittauri commented on common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepository.java
> +	List<JiraIssue> findByBasicProjectConfigIdIn(String basicProjectConfigId);
add java doc

2023-07-13 08:46 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java
> +	BACKLOG_COUNT_BY_STATUS("kpi151", Arrays.asList("Issue ID", "Issue Description", "Issue Type",
excel column script has to added

2023-07-13 08:47 UTC, Chittauri commented on customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImplTest.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
copyright

2023-07-13 08:47 UTC, Chittauri commented on customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByIssueTypeServiceImplTest.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
copyright

2023-07-13 08:48 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
copyright

2023-07-13 08:51 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +		leafNodeList.sort((node1, node2) -> node1.getSprintFilter().getStartDate()
why do we need to sort the sprint filter?

2023-07-13 08:56 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +			String basicProjectConfigId = leafNode.getProjectFilter().getBasicProjectConfigId().toString();
in backlog we need to get those statuses which are not tagged to sprint, check other kpis implementation, there are no checks present like that. please confirm.

2023-07-13 08:57 UTC, Chittauri commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByIssueTypeServiceImpl.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
check comments on BacklogCountByStatusType, implement same on this class

2023-07-13 09:01 UTC, hirbabar requested changes

2023-07-13 09:01 UTC, hirbabar commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByIssueTypeServiceImpl.java
> +			log.info("typeWiseIssuesList ->  : {}", typeWiseIssuesList);
typeWiseIssuesList -> remove unnecessary logs

2023-07-13 09:37 UTC, aksshriv1 commented on common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepository.java
> +	List<JiraIssue> findByBasicProjectConfigIdIn(String basicProjectConfigId);
added

2023-07-13 09:49 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java
> +	BACKLOG_COUNT_BY_STATUS("kpi151", Arrays.asList("Issue ID", "Issue Description", "Issue Type",
Script is added

2023-07-13 09:51 UTC, aksshriv1 commented on customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImplTest.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
added

2023-07-13 09:51 UTC, aksshriv1 commented on customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByIssueTypeServiceImplTest.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
added

2023-07-13 09:51 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +package com.publicissapient.kpidashboard.apis.jira.scrum.service;
added

2023-07-13 09:53 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +		leafNodeList.sort((node1, node2) -> node1.getSprintFilter().getStartDate()
There is no need of this so removing this piece of code.

2023-07-13 09:57 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByIssueTypeServiceImpl.java
> +			log.info("typeWiseIssuesList ->  : {}", typeWiseIssuesList);
removed

2023-07-13 10:17 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +			String basicProjectConfigId = leafNode.getProjectFilter().getBasicProjectConfigId().toString();
I have verified with Sumit and harsh and as per them all jira issue are considered in the backlog

2023-07-13 10:18 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java
> +			String basicProjectConfigId = leafNode.getProjectFilter().getBasicProjectConfigId().toString();
Not possible as other KPI

2023-07-13 11:01 UTC, aksshriv1 commented on database-scripts/scripts/kpi_master_insert.js
> +      "thresholdValue": "",
done

2023-07-18 05:50 UTC, hirbabar approved these changes

2023-07-18 05:53 UTC, Chittauri approved these changes

2023-07-18 05:54 UTC, merged