changes for DTS-31261 (Backend changes)
PublicisSapient/PSknowHOW pull request #589
Opened 2024-01-31 13:29 UTC by deepaktandn

changes for DTS-31261 (Backend changes ): As discussed with Brahmanand I have done the backend changes for Flow Efficiency and Lead Time filters.

2024-02-01 04:18 UTC, shunaray commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/FlowEfficiencyServiceImpl.java
> +import java.util.*;
remove wildcard imports

2024-02-01 04:26 UTC, shunaray requested changes
use correct formatter whole file is shown changed.

2024-02-01 04:29 UTC, shunaray commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/LeadTimeServiceImpl.java
> +import org.hamcrest.collection.IsEmptyCollection;
use  proper imports of collections

2024-02-01 07:23 UTC, shunaray requested changes
Reformat with correct file formatter, whole file is showing changed, can't be reviewed.

2024-02-01 07:23 UTC, shunaray commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/FlowEfficiencyServiceImpl.java
> +import com.publicissapient.kpidashboard.apis.model.*;
still wildcard imports !!

2024-02-01 09:03 UTC, kunkambl commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/FlowEfficiencyServiceImpl.java
> +        }
above code not needed and do those changes in setDataCountMap() method

2024-02-01 09:03 UTC, kunkambl commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/FlowEfficiencyServiceImpl.java
> -	}
Fix file formatting for both the files

2024-04-16 05:28 UTC, brahmanand1 commented
not needed hence closing and deleting branch

2024-04-16 05:28 UTC, closed without merging