Build frequency KPI for TEngine
PublicisSapient/PSknowHOW pull request #612
Opened 2024-02-05 18:55 UTC by aksshriv1

2024-02-06 04:33 UTC, purushottam08 approved these changes

2024-02-06 04:33 UTC, purushottam08 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImpl.java
> +						jobName = buildList.get(0).getJobFolder() + CommonConstant.ARROW + trendLineName;
No need of this here, do it directly in prepareinfoforbuild that way jobname is not needed as argument.

2024-02-06 05:11 UTC, shunaray requested changes
Missing:
Coverage
Mongock changes
Fieldmappingdto changes

2024-02-06 12:23 UTC, aksshriv1 commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImpl.java
> +						jobName = buildList.get(0).getJobFolder() + CommonConstant.ARROW + trendLineName;
It is needed here.

2024-02-06 12:34 UTC, aksshriv1 commented
Junit coverage is 85% of the developed feature

2024-02-06 12:51 UTC, shunaray commented on common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
> +	private String thresholdValueKPI172;
fieldmapping enum is not present

2024-02-06 12:51 UTC, shunaray commented on customapi/src/main/resources/json/mongock/default/kpi_master.json
> +    "kanban": false,
enter instance thresholdValue as in req, also bg color for threshold is missing

2024-02-06 12:51 UTC, shunaray commented on customapi/src/main/resources/json/mongock/default/kpi_master.json
> +    "showTrend": true,
-ve positiveTrend kpi ?

2024-02-06 12:51 UTC, shunaray commented on customapi/src/main/resources/json/mongock/default/kpi_category_mapping.json
> +  {
for internal client speed dashboard,

2024-02-06 12:51 UTC, shunaray commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
> +			excelData.setWeeks(buildFrequencyInfo.getWeeksList().get(i));
check once date format DD/MMM/YY

2024-02-06 12:51 UTC, shunaray commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImpl.java
> +	private boolean checkDateIsInWeeks(LocalDate monday, LocalDate sunday, Build build) {
use dateUtils method

2024-02-06 13:03 UTC, shunaray commented on customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImpl.java
> +	@Override
add missing javadoc

2024-02-08 10:45 UTC, aksshriv1 commented on customapi/src/main/resources/json/mongock/default/kpi_master.json
> +    "kanban": false,
done

2024-02-08 11:38 UTC, shunaray approved these changes

2024-02-09 04:23 UTC, merged