DTS-31005: Code cleanup for Auth
PublicisSapient/PSknowHOW pull request #631
Opened 2024-02-12 07:15 UTC by risshukl0

2024-02-12 09:46 UTC, HinPublicis requested changes

2024-02-12 09:46 UTC, HinPublicis commented on UI/src/app/services/app-initializer.service.ts
> +    // this.validateToken();
@risshukl0 why did you comment this?

2024-02-12 09:46 UTC, HinPublicis commented on UI/src/app/services/sso.guard.ts
> +    return this.getSSOUserInfo();
@risshukl0 we will require environment.SSO_LOGIN check here

2024-02-14 08:54 UTC, risshukl0 commented on UI/src/app/services/app-initializer.service.ts
> +    // this.validateToken();
I don't remember removing this function call. Might have done by mistake. Restored.

2024-02-14 09:44 UTC, risshukl0 commented on UI/src/app/services/sso.guard.ts
> +    return this.getSSOUserInfo();
Fixed. Taken code from master.

2024-02-29 12:03 UTC, closed without merging