UI_Pending Dts 36149 defect count by
PublicisSapient/PSknowHOW pull request #946
Opened 2024-05-14 09:05 UTC by Chittauri

2024-05-22 08:41 UTC, hirbabar approved these changes

2024-05-22 08:47 UTC, shunaray approved these changes

2024-05-22 13:34 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +        [style]="{'margin-left': '15px','background-color':'#fff', 'color': '#333333', 'border': '1px solid #333333', 'height': '30px', 'font-size': '10px'}"></p-button>
@risshukl0 please move the styles to css file

2024-05-22 13:34 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +  <div class="dialog-body p-mb-4">
@risshukl0 can we not use the same component for table like other dashboards.

2024-05-22 13:34 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +            <i class="pi pi-filter-slash" (click)="clearFilter(i)"></i>
@risshukl0 we should create a separate component for such a filter which we can reuse somewhere else as well.

2024-05-22 13:36 UTC, risshukl0 commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +            <i class="pi pi-filter-slash" (click)="clearFilter(i)"></i>
This component itself can be used anywhere, provided the json format remains same.

2024-05-22 13:38 UTC, risshukl0 commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +  <div class="dialog-body p-mb-4">
No Hinal, this component is designed to be completely self-contained. The explore button uses the common component.

2024-05-22 14:04 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +  <div class="dialog-body p-mb-4">
@risshukl0 I am talking about the new filter popup that you added. That can be an independent component.

2024-05-22 14:08 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +        [style]="{'margin-left': '15px','background-color':'#fff', 'color': '#333333', 'border': '1px solid #333333', 'height': '30px', 'font-size': '10px'}"></p-button>
did you try to use :host ::ng-deep?

2024-05-23 04:25 UTC, risshukl0 commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +        [style]="{'margin-left': '15px','background-color':'#fff', 'color': '#333333', 'border': '1px solid #333333', 'height': '30px', 'font-size': '10px'}"></p-button>
yes. I tried.

2024-05-23 04:26 UTC, risshukl0 commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.html
> +            <i class="pi pi-filter-slash" (click)="clearFilter(i)"></i>
It won't work, because the filter takes into account the modified data from the main filter tabs as well.

2024-05-28 07:34 UTC, HinPublicis requested changes

2024-05-28 07:34 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.ts
> +    setTimeout(() => this.draw(this.modifiedData), 100);
@risshukl0 why do we need settimeout here?

2024-05-28 07:34 UTC, HinPublicis commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.ts
> +    setTimeout(() => this.draw(this.modifiedData), 100);
@risshukl0 why do we need settimeout here?

2024-05-28 07:36 UTC, risshukl0 commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.ts
> +    setTimeout(() => this.draw(this.modifiedData), 100);
setTimeOut is required to take the draw function out of the event loop, because if not the *ngIf doesn't allow the chart to appear

2024-05-28 07:36 UTC, risshukl0 commented on UI/src/app/component/chart-with-filters/chart-with-filters.component.ts
> +    setTimeout(() => this.draw(this.modifiedData), 100);
setTimeOut is required to take the draw function out of the event loop, because if not the *ngIf doesn't allow the chart to appear

2024-05-28 07:44 UTC, HinPublicis approved these changes

2024-05-28 07:51 UTC, merged